version: "3"

services:
  pgAdmin:
    restart: always
    image: dpage/pgadmin4
    ports:
      - "5000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    depends_on:
        - postgres

  postgres:
    restart: always
    image: postgres
    user: "1000"
    container_name: "${DATABASE_CONTAINER_NAME}"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  php-fpm:
    restart: always
    # container_name: "php-fpm"
    user: "1000"
    build:
      context: ./php-fpm
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_CONTAINER_NAME}:5432/${DATABASE_NAME}?serverVersion=11&charset=utf8
    volumes:
      - ./code:/var/www
      - ./php-fpm/www.conf:/etc/php7/php-fpm.d/www.conf:ro
    depends_on:
        - postgres

  nginx:
    restart: always
    image: nginx:alpine
    volumes:
      - ./code:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "8080:80"
      - "443:443"
    links:
      - php-fpm
